name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  # Common versions
  GO_VERSION: "1.23.8"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build
        run: go build -v ./...
