name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  # Common versions
  GO_VERSION: "1.17"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: go build -v ./...
